### ISSUE TITLE
[Feature request] Make a version that can be used as a theme on a Lemmy server

### ISSUE THREAD

**Issue by bernarddavis** [soundjester/lemmy_monkey#14]
Not sure if this is even possible, but it would be great if a version of this theme were made available to install on a Lemmy server and use as a theme

**Comment by soundjester** [comment]
Unfortunately, discussions in that direction have revealed that this isn't really a good candidate for a theme.  Rather than applying colors and making minor look/feel adjustments (eg, square corners instead of rounded), this is making large structural changes to the underlying bootstrap CSS.

further discussion here: https://sh.itjust.works/comment/347077

The changes applied by this script would probably need to be incorporated as a fork of Lemmy's main bootstrap CSS - then have various theming applied.
